import {
  Binary,
  Braces,
  CalendarDays,
  Clock3,
  Code2,
  Database,
  Diff,
  FileArchive,
  FileCode2,
  FileText,
  Fingerprint,
  Globe2,
  Hash,
  Image as ImageIcon,
  KeyRound,
  LucideIcon,
  Mic2,
  Network,
  Podcast,
  Regex,
  ScanSearch,
  Server,
  ShieldCheck,
  Table2,
  TerminalSquare,
  TimerReset,
  Wand2,
} from 'lucide-react';
import { FILE_LIMITS } from '@/lib/file-limits';
import type { ModulePrivacySpec } from '@/lib/privacy';

export type ToolStatus = 'live' | 'planned' | 'ai-opt-in';
export type ToolInputMode = 'text' | 'file' | 'form';

export type ToolDefinition = {
  id: string;
  slug: string;
  name: string;
  description: string;
  category: string;
  icon: LucideIcon;
  keywords: string[];
  priority: number;
  status: ToolStatus;
  inputMode: ToolInputMode;
  accept?: string;
  spec: ModulePrivacySpec;
  useCases: string[];
};

export type ToolCategory = {
  id: string;
  name: string;
  description: string;
  icon: LucideIcon;
  tools: ToolDefinition[];
};

const localTextSpec = (module: string, notes: string): ModulePrivacySpec => ({
  module,
  engine: 'typescript',
  maxInputBytes: FILE_LIMITS.text,
  notes,
});

const workerTextSpec = (module: string, notes: string): ModulePrivacySpec => ({
  module,
  engine: 'worker',
  maxInputBytes: FILE_LIMITS.text,
  notes,
});

export const TOOL_CATEGORIES: ToolCategory[] = [
  {
    id: 'core-dev',
    name: 'Core Developer',
    description: 'Daily API, auth, encoding, text, and config utilities.',
    icon: Code2,
    tools: [
      {
        id: 'json-format',
        slug: 'json-formatter',
        name: 'JSON Formatter',
        description: 'Format, validate, and inspect API payloads and config files.',
        category: 'Core Developer',
        icon: Braces,
        keywords: ['json', 'formatter', 'validator', 'minifier', 'api', 'payload'],
        priority: 1,
        status: 'live',
        inputMode: 'text',
        spec: localTextSpec('devtools', 'JSON parsing runs in this tab only.'),
        useCases: ['Format API responses', 'Validate config files', 'Minify payloads'],
      },
      {
        id: 'jwt-decoder',
        slug: 'jwt-decoder',
        name: 'JWT Decoder',
        description: 'Decode JWT headers and claims locally without sending tokens anywhere.',
        category: 'Core Developer',
        icon: KeyRound,
        keywords: ['jwt', 'token', 'auth', 'claims', 'oauth', 'openid'],
        priority: 2,
        status: 'live',
        inputMode: 'text',
        spec: localTextSpec('devtools', 'Token decoding is local; signature verification is never uploaded.'),
        useCases: ['Inspect auth claims', 'Debug token expiry', 'Review issuer and audience'],
      },
      {
        id: 'base64',
        slug: 'base64-encoder-decoder',
        name: 'Base64 Encode/Decode',
        description: 'Encode and decode Unicode-safe Base64 strings.',
        category: 'Core Developer',
        icon: Binary,
        keywords: ['base64', 'encode', 'decode', 'authorization', 'basic auth'],
        priority: 3,
        status: 'live',
        inputMode: 'text',
        spec: localTextSpec('devtools', 'Encoding happens in memory.'),
        useCases: ['Debug auth headers', 'Decode API payload fragments', 'Encode test strings'],
      },
      {
        id: 'url-codec',
        slug: 'url-encoder-decoder',
        name: 'URL Encode/Decode',
        description: 'Encode and decode URLs, query strings, redirects, and webhook payloads.',
        category: 'Core Developer',
        icon: Globe2,
        keywords: ['url', 'encode', 'decode', 'query string', 'webhook'],
        priority: 4,
        status: 'live',
        inputMode: 'text',
        spec: localTextSpec('devtools', 'URL text never leaves the browser.'),
        useCases: ['Debug redirect URLs', 'Encode query params', 'Decode webhook data'],
      },
      {
        id: 'timestamp',
        slug: 'unix-timestamp-converter',
        name: 'Unix Timestamp Converter',
        description: 'Convert Unix timestamps to local and UTC date strings.',
        category: 'Core Developer',
        icon: Clock3,
        keywords: ['unix', 'timestamp', 'epoch', 'date', 'time', 'logs'],
        priority: 5,
        status: 'live',
        inputMode: 'text',
        spec: localTextSpec('devtools', 'Timestamp conversion uses browser date APIs.'),
        useCases: ['Read log timestamps', 'Debug API dates', 'Generate current epoch time'],
      },
      {
        id: 'uuid',
        slug: 'uuid-generator',
        name: 'UUID Generator',
        description: 'Generate UUID v4 values using the browser crypto API.',
        category: 'Core Developer',
        icon: Fingerprint,
        keywords: ['uuid', 'guid', 'id', 'random', 'test data'],
        priority: 6,
        status: 'live',
        inputMode: 'form',
        spec: localTextSpec('devtools', 'UUIDs are created with crypto.randomUUID.'),
        useCases: ['Create test IDs', 'Seed mock data', 'Generate correlation IDs'],
      },
      {
        id: 'hash',
        slug: 'hash-generator',
        name: 'Hash Generator',
        description: 'Generate MD5, SHA-1, SHA-256, SHA-384, and SHA-512 hashes.',
        category: 'Core Developer',
        icon: Hash,
        keywords: ['hash', 'checksum', 'sha256', 'sha1', 'md5'],
        priority: 7,
        status: 'live',
        inputMode: 'text',
        spec: localTextSpec('devtools', 'Hashing uses local browser crypto and local MD5 code.'),
        useCases: ['Create checksums', 'Compare payload hashes', 'Debug signature inputs'],
      },
      {
        id: 'regex-tester',
        slug: 'regex-tester',
        name: 'Regex Tester',
        description: 'Test JavaScript regular expressions against sample text.',
        category: 'Core Developer',
        icon: Regex,
        keywords: ['regex', 'regular expression', 'tester', 'match', 'validation'],
        priority: 8,
        status: 'live',
        inputMode: 'text',
        spec: localTextSpec('devtools', 'Pattern matching runs locally in the browser.'),
        useCases: ['Validate input rules', 'Parse logs', 'Test extraction patterns'],
      },
      {
        id: 'text-diff',
        slug: 'text-diff',
        name: 'Text Diff',
        description: 'Compare two text blocks line by line.',
        category: 'Core Developer',
        icon: Diff,
        keywords: ['diff', 'compare', 'text', 'config', 'logs'],
        priority: 9,
        status: 'live',
        inputMode: 'text',
        spec: localTextSpec('filetools', 'Diffing happens in memory.'),
        useCases: ['Compare configs', 'Review log differences', 'Check snippets'],
      },
      {
        id: 'json-diff',
        slug: 'json-diff',
        name: 'JSON Diff',
        description: 'Normalize and compare two JSON documents.',
        category: 'Core Developer',
        icon: Braces,
        keywords: ['json diff', 'compare json', 'api response', 'payload'],
        priority: 10,
        status: 'live',
        inputMode: 'text',
        spec: localTextSpec('devtools', 'JSON normalization and diffing are local.'),
        useCases: ['Compare API responses', 'Debug config drift', 'Normalize before diffing'],
      },
      {
        id: 'cron-parser',
        slug: 'cron-expression-parser',
        name: 'Cron Expression Parser',
        description: 'Explain common five-field cron expressions.',
        category: 'Core Developer',
        icon: TimerReset,
        keywords: ['cron', 'crontab', 'schedule', 'devops'],
        priority: 11,
        status: 'live',
        inputMode: 'text',
        spec: localTextSpec('devtools', 'Cron parsing is deterministic local TypeScript.'),
        useCases: ['Read scheduled jobs', 'Debug DevOps schedules', 'Explain cron syntax'],
      },
    ],
  },
  {
    id: 'api-data',
    name: 'API and Data',
    description: 'Converters and validators for backend/API workflows.',
    icon: Server,
    tools: [
      {
        id: 'yaml-json',
        slug: 'yaml-json-converter',
        name: 'YAML ⇄ JSON Converter',
        description: 'Convert YAML to JSON and JSON to YAML.',
        category: 'API and Data',
        icon: FileCode2,
        keywords: ['yaml', 'json', 'converter', 'config', 'openapi'],
        priority: 12,
        status: 'live',
        inputMode: 'text',
        spec: localTextSpec('devtools', 'YAML and JSON parsing stays in memory.'),
        useCases: ['Convert config files', 'Prepare API specs', 'Normalize manifests'],
      },
      {
        id: 'csv-json',
        slug: 'csv-json-converter',
        name: 'CSV ⇄ JSON Converter',
        description: 'Convert CSV to JSON and JSON arrays to CSV.',
        category: 'API and Data',
        icon: Table2,
        keywords: ['csv', 'json', 'converter', 'spreadsheet', 'data'],
        priority: 13,
        status: 'live',
        inputMode: 'text',
        accept: '.csv,application/json,text/csv',
        spec: localTextSpec('filetools', 'No spreadsheet data is uploaded.'),
        useCases: ['Prepare fixtures', 'Convert exports', 'Inspect table data'],
      },
      {
        id: 'xml-format',
        slug: 'xml-formatter',
        name: 'XML Formatter',
        description: 'Format and validate XML using browser DOM parsing.',
        category: 'API and Data',
        icon: FileCode2,
        keywords: ['xml', 'formatter', 'soap', 'sitemap'],
        priority: 14,
        status: 'live',
        inputMode: 'text',
        spec: localTextSpec('devtools', 'XML parsing uses the browser DOMParser locally.'),
        useCases: ['Format SOAP payloads', 'Validate XML snippets', 'Read sitemap XML'],
      },
      {
        id: 'excel-csv',
        slug: 'excel-to-csv',
        name: 'Excel to CSV',
        description: 'Convert the first Excel worksheet to CSV in the browser.',
        category: 'API and Data',
        icon: Table2,
        keywords: ['excel', 'xlsx', 'csv', 'spreadsheet', 'converter'],
        priority: 15,
        status: 'live',
        inputMode: 'file',
        accept: '.xlsx,.xls,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel',
        spec: localTextSpec('filetools', 'Excel parsing runs locally and output is generated in memory.'),
        useCases: ['Convert spreadsheets', 'Prepare CSV imports', 'Inspect workbook data'],
      },
      {
        id: 'excel-json',
        slug: 'excel-to-json',
        name: 'Excel to JSON',
        description: 'Convert Excel worksheets to JSON locally.',
        category: 'API and Data',
        icon: Table2,
        keywords: ['excel', 'xlsx', 'json', 'spreadsheet', 'converter'],
        priority: 16,
        status: 'live',
        inputMode: 'file',
        accept: '.xlsx,.xls,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel',
        spec: localTextSpec('filetools', 'Workbook data is parsed in browser memory only.'),
        useCases: ['Inspect spreadsheets', 'Build fixtures', 'Convert workbook sheets'],
      },
      {
        id: 'openapi-validator',
        slug: 'openapi-validator',
        name: 'OpenAPI Validator',
        description: 'Validate OpenAPI JSON/YAML and surface schema issues.',
        category: 'API and Data',
        icon: Network,
        keywords: ['openapi', 'swagger', 'api', 'validator'],
        priority: 20,
        status: 'live',
        inputMode: 'text',
        spec: localTextSpec('api', 'OpenAPI structure validation runs locally without uploading specs.'),
        useCases: ['Validate API contracts', 'Review Swagger files', 'Prepare docs'],
      },
      {
        id: 'curl-converter',
        slug: 'curl-converter',
        name: 'cURL Converter',
        description: 'Convert cURL commands to C#, JavaScript, Python, or fetch.',
        category: 'API and Data',
        icon: TerminalSquare,
        keywords: ['curl', 'converter', 'http', 'fetch', 'csharp', 'python'],
        priority: 21,
        status: 'live',
        inputMode: 'text',
        spec: localTextSpec('api', 'cURL parsing and code generation stay in this tab.'),
        useCases: ['Create SDK examples', 'Move requests between tools', 'Document APIs'],
      },
    ],
  },
  {
    id: 'ai-engineering',
    name: 'AI Engineering',
    description: 'Privacy-aware AI utilities, local where possible and opt-in online where needed.',
    icon: Wand2,
    tools: [
      {
        id: 'token-estimator',
        slug: 'llm-token-estimator',
        name: 'LLM Token Estimator',
        description: 'Estimate prompt tokens and approximate model cost locally.',
        category: 'AI Engineering',
        icon: ScanSearch,
        keywords: ['llm', 'token', 'openai', 'azure openai', 'cost'],
        priority: 30,
        status: 'live',
        inputMode: 'text',
        spec: localTextSpec('ai', 'Approximate token counting runs locally; no model call is made.'),
        useCases: ['Estimate prompt cost', 'Size RAG chunks', 'Debug token limits'],
      },
      {
        id: 'prompt-diff',
        slug: 'prompt-diff',
        name: 'Prompt Diff',
        description: 'Compare prompt versions and highlight behavioral changes.',
        category: 'AI Engineering',
        icon: Diff,
        keywords: ['prompt', 'diff', 'ai', 'llm', 'evaluation'],
        priority: 31,
        status: 'live',
        inputMode: 'text',
        spec: localTextSpec('filetools', 'Prompt comparison uses local diff logic.'),
        useCases: ['Compare prompt versions', 'Review system prompts', 'Track eval changes'],
      },
      {
        id: 'json-schema-generator',
        slug: 'json-schema-generator',
        name: 'JSON Schema Generator',
        description: 'Generate JSON Schema from sample JSON for API and LLM outputs.',
        category: 'AI Engineering',
        icon: Database,
        keywords: ['json schema', 'schema', 'structured outputs', 'api'],
        priority: 32,
        status: 'live',
        inputMode: 'text',
        spec: localTextSpec('ai', 'Schema inference runs locally; no model needed for MVP.'),
        useCases: ['Design structured outputs', 'Validate API payloads', 'Create test schemas'],
      },
      {
        id: 'ebook-podcast',
        slug: 'ebook-to-podcast',
        name: 'Ebook to Podcast',
        description: 'Convert EPUB/PDF chapters into podcast-style audio.',
        category: 'AI Engineering',
        icon: Podcast,
        keywords: ['ebook', 'podcast', 'tts', 'epub', 'audio', 'openai'],
        priority: 40,
        status: 'ai-opt-in',
        inputMode: 'file',
        accept: '.epub,application/pdf',
        spec: {
          module: 'ai',
          engine: 'worker',
          maxInputBytes: FILE_LIMITS.pdf,
          notes: 'Requires opt-in model calls or user-provided API key; not part of strict offline mode.',
        },
        useCases: ['Listen to documents', 'Create study audio', 'Summarize long ebooks'],
      },
      {
        id: 'site-podcast',
        slug: 'site-to-podcast',
        name: 'Site to Podcast',
        description: 'Turn a public article or site into narrated audio.',
        category: 'AI Engineering',
        icon: Mic2,
        keywords: ['site', 'article', 'podcast', 'tts', 'audio', 'openai'],
        priority: 41,
        status: 'ai-opt-in',
        inputMode: 'form',
        spec: {
          module: 'ai',
          engine: 'worker',
          maxInputBytes: FILE_LIMITS.text,
          notes: 'Fetching remote pages and TTS require explicit online mode.',
        },
        useCases: ['Listen to articles', 'Create briefing audio', 'Convert docs to speech'],
      },
    ],
  },
  {
    id: 'code-runtime',
    name: 'Code and Runtime',
    description: 'Browser runtimes first, with explicit Online Mode for full backend compilers.',
    icon: TerminalSquare,
    tools: [
      {
        id: 'python-compiler',
        slug: 'python-online-compiler',
        name: 'Python Online Compiler',
        description: 'Run Python snippets with Pyodide in a worker, with optional online fallback later.',
        category: 'Code and Runtime',
        icon: TerminalSquare,
        keywords: ['python', 'compiler', 'pyodide', 'runner', 'code execution'],
        priority: 42,
        status: 'live',
        inputMode: 'text',
        spec: {
          module: 'runtime',
          engine: 'wasm-worker',
          maxInputBytes: FILE_LIMITS.text,
          notes: 'Use Pyodide in a dedicated worker; package installs must be explicit and network-blocked by default.',
        },
        useCases: ['Test Python snippets', 'Run data transforms', 'Practice interview examples'],
      },
      {
        id: 'javascript-compiler',
        slug: 'javascript-online-compiler',
        name: 'JavaScript Runner',
        description: 'Execute JavaScript snippets inside an isolated worker with timeout protection.',
        category: 'Code and Runtime',
        icon: Code2,
        keywords: ['javascript', 'compiler', 'runner', 'sandbox', 'worker'],
        priority: 43,
        status: 'live',
        inputMode: 'text',
        spec: workerTextSpec('runtime', 'Run code in a disposable worker with CPU timeout and output limits.'),
        useCases: ['Test small JS snippets', 'Debug algorithms', 'Inspect console output'],
      },
      {
        id: 'typescript-playground',
        slug: 'typescript-playground',
        name: 'TypeScript Playground',
        description: 'Transpile TypeScript in the browser and inspect JavaScript output.',
        category: 'Code and Runtime',
        icon: FileCode2,
        keywords: ['typescript', 'playground', 'transpile', 'compiler'],
        priority: 44,
        status: 'live',
        inputMode: 'text',
        spec: workerTextSpec('runtime', 'Bundle the TypeScript compiler in a worker; no source upload.'),
        useCases: ['Check TS syntax', 'Inspect emitted JS', 'Prototype utility types'],
      },
      {
        id: 'html-css-js-editor',
        slug: 'html-css-js-live-editor',
        name: 'HTML CSS JS Editor',
        description: 'Preview frontend snippets in a sandboxed iframe.',
        category: 'Code and Runtime',
        icon: FileCode2,
        keywords: ['html', 'css', 'javascript', 'live editor', 'iframe', 'frontend'],
        priority: 45,
        status: 'live',
        inputMode: 'text',
        spec: {
          module: 'runtime',
          engine: 'iframe',
          maxInputBytes: FILE_LIMITS.text,
          notes: 'Use a sandboxed iframe without same-origin access; block persistence and default network workflows.',
        },
        useCases: ['Test HTML snippets', 'Preview CSS', 'Prototype UI fragments'],
      },
      {
        id: 'sql-compiler',
        slug: 'sql-online-compiler',
        name: 'SQL Online Compiler',
        description: 'Run SQLite queries locally with SQLite WASM.',
        category: 'Code and Runtime',
        icon: Database,
        keywords: ['sql', 'sqlite', 'compiler', 'query', 'database', 'wasm'],
        priority: 46,
        status: 'live',
        inputMode: 'text',
        spec: {
          module: 'runtime',
          engine: 'wasm-worker',
          maxInputBytes: FILE_LIMITS.text,
          notes: 'Load SQLite WASM in a worker and keep tables in memory only.',
        },
        useCases: ['Test SQL queries', 'Analyze CSV data', 'Practice SQLite syntax'],
      },
      {
        id: 'wasm-runner',
        slug: 'webassembly-runner',
        name: 'WebAssembly Runner',
        description: 'Inspect and run simple no-import WASM modules locally.',
        category: 'Code and Runtime',
        icon: TerminalSquare,
        keywords: ['wasm', 'webassembly', 'runner', 'module', 'exports'],
        priority: 47,
        status: 'live',
        inputMode: 'file',
        accept: '.wasm,application/wasm',
        spec: {
          module: 'runtime',
          engine: 'wasm',
          maxInputBytes: FILE_LIMITS.text,
          notes: 'WASM modules are compiled and instantiated by the browser only.',
        },
        useCases: ['Inspect WASM exports', 'Run simple WASM functions', 'Debug local modules'],
      },
      {
        id: 'rust-wasm-notes',
        slug: 'rust-to-wasm-notes',
        name: 'Rust to WASM Notes',
        description: 'Generate a local Rust-to-WASM build checklist and starter commands.',
        category: 'Code and Runtime',
        icon: FileCode2,
        keywords: ['rust', 'wasm', 'wasm-pack', 'guide', 'commands'],
        priority: 48,
        status: 'live',
        inputMode: 'form',
        spec: localTextSpec('runtime', 'This helper generates local setup notes only; no code is uploaded.'),
        useCases: ['Prepare wasm-pack setup', 'Document build steps', 'Plan browser WASM modules'],
      },
    ],
  },
  {
    id: 'files-media',
    name: 'Files and Media',
    description: 'WASM-backed file, PDF, archive, calendar, and image tools.',
    icon: FileArchive,
    tools: [
      {
        id: 'pdf-merge',
        slug: 'pdf-merge',
        name: 'Merge PDFs',
        description: 'Combine PDF files locally with QPDF WASM inside a worker.',
        category: 'Files and Media',
        icon: FileText,
        keywords: ['pdf', 'merge', 'combine', 'qpdf', 'wasm'],
        priority: 50,
        status: 'live',
        inputMode: 'file',
        accept: '.pdf,application/pdf',
        spec: {
          module: 'pdf',
          engine: 'wasm-worker',
          maxInputBytes: FILE_LIMITS.pdf,
          notes: 'ArrayBuffers are copied into QPDF virtual memory only.',
        },
        useCases: ['Combine contracts', 'Merge reports', 'Prepare submissions'],
      },
      {
        id: 'pdf-epub',
        slug: 'pdf-to-epub',
        name: 'PDF to EPUB',
        description: 'Convert PDF documents into EPUB packages.',
        category: 'Files and Media',
        icon: FileText,
        keywords: ['pdf', 'epub', 'ebook', 'converter'],
        priority: 51,
        status: 'live',
        inputMode: 'file',
        accept: '.pdf,application/pdf',
        spec: {
          module: 'pdf',
          engine: 'wasm-worker',
          maxInputBytes: FILE_LIMITS.pdf,
          notes: 'Use MuPDF/PDFium WASM for extraction and Rust WASM for EPUB packaging.',
        },
        useCases: ['Create ebooks', 'Read PDFs on e-readers', 'Package chapter text'],
      },
      {
        id: 'image-convert',
        slug: 'image-converter',
        name: 'Image Converter',
        description: 'Convert PNG, JPG, and WebP with WASM image codecs.',
        category: 'Files and Media',
        icon: ImageIcon,
        keywords: ['image', 'png', 'jpg', 'jpeg', 'webp', 'convert', 'compress'],
        priority: 52,
        status: 'live',
        inputMode: 'file',
        accept: 'image/png,image/jpeg,image/webp',
        spec: {
          module: 'image',
          engine: 'wasm-worker',
          maxInputBytes: FILE_LIMITS.image,
          notes: 'Pixels are decoded and encoded in a worker.',
        },
        useCases: ['Convert screenshots', 'Compress images', 'Prepare web assets'],
      },
      {
        id: 'image-compress',
        slug: 'image-compressor',
        name: 'Image Compressor',
        description: 'Compress PNG, JPG, and WebP images locally with WASM codecs.',
        category: 'Files and Media',
        icon: ImageIcon,
        keywords: ['image', 'compress', 'png', 'jpg', 'jpeg', 'webp', 'wasm'],
        priority: 53,
        status: 'live',
        inputMode: 'file',
        accept: 'image/png,image/jpeg,image/webp',
        spec: {
          module: 'image',
          engine: 'wasm-worker',
          maxInputBytes: FILE_LIMITS.image,
          notes: 'Image compression runs in a worker; files remain in memory.',
        },
        useCases: ['Reduce screenshots', 'Prepare web images', 'Compress uploads before sharing'],
      },
      {
        id: 'image-resize',
        slug: 'image-resizer',
        name: 'Image Resizer',
        description: 'Resize images locally while preserving the input format.',
        category: 'Files and Media',
        icon: ImageIcon,
        keywords: ['image', 'resize', 'dimensions', 'png', 'jpg', 'webp'],
        priority: 54,
        status: 'live',
        inputMode: 'file',
        accept: 'image/png,image/jpeg,image/webp',
        spec: {
          module: 'image',
          engine: 'wasm-worker',
          maxInputBytes: FILE_LIMITS.image,
          notes: 'Image resizing uses OffscreenCanvas in the image worker.',
        },
        useCases: ['Resize screenshots', 'Create thumbnails', 'Prepare fixed-size assets'],
      },
      {
        id: 'base64-image',
        slug: 'base64-image-converter',
        name: 'Base64 Image Converter',
        description: 'Convert images to and from Base64 data URLs.',
        category: 'Files and Media',
        icon: ImageIcon,
        keywords: ['image', 'base64', 'data url', 'converter'],
        priority: 55,
        status: 'live',
        inputMode: 'file',
        accept: 'image/*',
        spec: {
          module: 'image',
          engine: 'typescript',
          maxInputBytes: FILE_LIMITS.image,
          notes: 'Data URLs are generated in memory.',
        },
        useCases: ['Embed small images', 'Decode data URLs', 'Inspect image payloads'],
      },
      {
        id: 'ics-generator',
        slug: 'ics-generator',
        name: 'ICS Generator',
        description: 'Create single or recurring calendar events as downloadable ICS.',
        category: 'Files and Media',
        icon: CalendarDays,
        keywords: ['ics', 'calendar', 'event', 'recurring'],
        priority: 56,
        status: 'live',
        inputMode: 'form',
        spec: {
          module: 'calendar',
          engine: 'typescript',
          maxInputBytes: FILE_LIMITS.calendar,
          notes: 'Generated text never touches a server.',
        },
        useCases: ['Generate invites', 'Create recurring events', 'Download calendar files'],
      },
      {
        id: 'zip-tools',
        slug: 'zip-unzip',
        name: 'ZIP / UNZIP',
        description: 'Compress and extract archives in the browser.',
        category: 'Files and Media',
        icon: FileArchive,
        keywords: ['zip', 'unzip', 'archive', 'compress', 'extract'],
        priority: 57,
        status: 'live',
        inputMode: 'file',
        accept: '.zip,application/zip',
        spec: {
          module: 'filetools',
          engine: 'wasm-worker',
          maxInputBytes: FILE_LIMITS.archive,
          notes: 'Start with fflate worker; move hot paths to Rust WASM if needed.',
        },
        useCases: ['Inspect archives', 'Compress files locally', 'Extract ZIPs privately'],
      },
    ],
  },
  {
    id: 'security-lite',
    name: 'Security Lite',
    description: 'Browser-only helpers for auth, keys, certificates, and headers.',
    icon: ShieldCheck,
    tools: [
      {
        id: 'password-generator',
        slug: 'password-generator',
        name: 'Password Generator',
        description: 'Generate strong passwords locally with browser crypto.',
        category: 'Security Lite',
        icon: ShieldCheck,
        keywords: ['password', 'generator', 'security', 'random'],
        priority: 60,
        status: 'live',
        inputMode: 'form',
        spec: localTextSpec('security', 'Passwords are generated with crypto.getRandomValues.'),
        useCases: ['Generate temp passwords', 'Create test secrets', 'Avoid server-side generation'],
      },
      {
        id: 'certificate-decoder',
        slug: 'certificate-decoder',
        name: 'Certificate Decoder',
        description: 'Decode PEM certificates and inspect subject, issuer, and expiry.',
        category: 'Security Lite',
        icon: ShieldCheck,
        keywords: ['certificate', 'pem', 'x509', 'tls', 'ssl'],
        priority: 61,
        status: 'live',
        inputMode: 'text',
        spec: localTextSpec('security', 'PEM inspection runs locally with a lightweight DER string parser.'),
        useCases: ['Check cert expiry', 'Inspect issuer', 'Debug TLS chains'],
      },
    ],
  },
];

export const ALL_TOOLS = TOOL_CATEGORIES.flatMap((category) => category.tools).sort((a, b) => a.priority - b.priority);
export const LIVE_TOOLS = ALL_TOOLS.filter((tool) => tool.status === 'live');
export const FEATURED_TOOLS = ALL_TOOLS.filter((tool) => tool.priority <= 15);

export function findTool(toolIdOrSlug: string) {
  return ALL_TOOLS.find((tool) => tool.id === toolIdOrSlug || tool.slug === toolIdOrSlug) ?? ALL_TOOLS[0];
}

export function findCategoryForTool(toolId: string) {
  return TOOL_CATEGORIES.find((category) => category.tools.some((tool) => tool.id === toolId));
}

export function searchTools(query: string, tools: readonly ToolDefinition[] = ALL_TOOLS) {
  const normalized = query.trim().toLowerCase();
  if (!normalized) return tools;

  return tools.filter((tool) =>
    [tool.name, tool.description, tool.category, tool.slug, ...tool.keywords]
      .filter(Boolean)
      .some((value) => value?.toLowerCase().includes(normalized)),
  );
}
